from omniload.core.model import LazyRegistry

SQL_SOURCE_SCHEMES = [
    "bigquery",
    "crate",
    "cratedb",
    "duckdb",
    "mssql",
    "mssql+pyodbc",
    "mysql",
    "mysql+pymysql",
    "mysql+mysqlconnector",
    "md",
    "motherduck",
    "postgres",
    "postgresql",
    "postgresql+psycopg2",
    "redshift",
    "redshift+psycopg2",
    "snowflake",
    "sqlite",
    "oracle",
    "oracle+cx_oracle",
    "oracle+oracledb",
    "hana",
    "clickhouse",
    "databricks",
    "db2",
    "spanner",
    "trino",
]

sources: LazyRegistry = LazyRegistry(
    {
        "adjust": "omniload.source.adjust.api:AdjustSource",
        "airtable": "omniload.source.airtable.api:AirtableSource",
        "allium": "omniload.source.allium.api:AlliumSource",
        "amqp+mqb": "omniload.source.mqbridge.api:MqBridgeSource",
        "anthropic": "omniload.source.anthropic.api:AnthropicSource",
        "applovin": "omniload.source.applovin.api:AppLovinSource",
        "applovinmax": "omniload.source.applovin_max.api:ApplovinMaxSource",
        "appsflyer": "omniload.source.appsflyer.api:AppsflyerSource",
        "appstore": "omniload.source.appstore.api:AppleAppStoreSource",
        "asana": "omniload.source.asana.api:AsanaSource",
        "attio": "omniload.source.attio.api:AttioSource",
        "aws+mqb": "omniload.source.mqbridge.api:MqBridgeSource",
        "bruin": "omniload.source.bruin.api:BruinSource",
        "chess": "omniload.source.chess.api:ChessSource",
        "clickup": "omniload.source.clickup.api:ClickupSource",
        "couchbase": "omniload.source.couchbase.api:CouchbaseSource",
        "csv": "omniload.source.csv.api:LocalCsvSource",
        "cursor": "omniload.source.cursor.api:CursorSource",
        "customerio": "omniload.source.customer_io.api:CustomerIoSource",
        "docebo": "omniload.source.docebo.api:DoceboSource",
        "dune": "omniload.source.dune.api:DuneSource",
        "dynamodb": "omniload.source.dynamodb.api:DynamoDBSource",
        "elasticsearch": "omniload.source.elasticsearch.api:ElasticsearchSource",
        "facebookads": "omniload.source.facebook_ads.api:FacebookAdsSource",
        "fireflies": "omniload.source.fireflies.api:FirefliesSource",
        "fluxx": "omniload.source.fluxx.api:FluxxSource",
        "frankfurter": "omniload.source.frankfurter.api:FrankfurterSource",
        "freshdesk": "omniload.source.freshdesk.api:FreshdeskSource",
        "fundraiseup": "omniload.source.fundraiseup.api:FundraiseupSource",
        "github": "omniload.source.github.api:GitHubSource",
        "googleads": "omniload.source.google_ads.api:GoogleAdsSource",
        "googleanalytics": "omniload.source.google_analytics.api:GoogleAnalyticsSource",
        "gorgias": "omniload.source.gorgias.api:GorgiasSource",
        "gs": "omniload.source.blobstorage.api:GCSSource",
        "gsheets": "omniload.source.google_sheets.api:GoogleSheetsSource",
        "hostaway": "omniload.source.hostaway.api:HostawaySource",
        "http": "omniload.source.http.api:HttpSource",
        "https": "omniload.source.http.api:HttpSource",
        "hubspot": "omniload.source.hubspot.api:HubspotSource",
        "ibmmq+mqb": "omniload.source.mqbridge.api:MqBridgeSource",
        "indeed": "omniload.source.indeed.api:IndeedSource",
        "influxdb": "omniload.source.influxdb.api:InfluxDBSource",
        "intercom": "omniload.source.intercom.api:IntercomSource",
        "isoc-pulse": "omniload.source.isoc_pulse.api:IsocPulseSource",
        "jira": "omniload.source.jira.api:JiraSource",
        "kafka": "omniload.source.kafka.api:KafkaSource",
        "kafka+mqb": "omniload.source.mqbridge.api:MqBridgeSource",
        "kinesis": "omniload.source.kinesis.api:KinesisSource",
        "klaviyo": "omniload.source.klaviyo.api:KlaviyoSource",
        "linear": "omniload.source.linear.api:LinearSource",
        "linkedinads": "omniload.source.linkedin_ads.api:LinkedInAdsSource",
        "mailchimp": "omniload.source.mailchimp.api:MailchimpSource",
        "memory+mqb": "omniload.source.mqbridge.api:MqBridgeSource",
        "mixpanel": "omniload.source.mixpanel.api:MixpanelSource",
        "mmap": "omniload.source.arrow.api:ArrowMemoryMappedSource",
        "monday": "omniload.source.monday.api:MondaySource",
        "mongodb": "omniload.source.mongodb.api:MongoDbSource",
        "mongodb+srv": "omniload.source.mongodb.api:MongoDbSource",
        "mqtt+mqb": "omniload.source.mqbridge.api:MqBridgeSource",
        "nats+mqb": "omniload.source.mqbridge.api:MqBridgeSource",
        "notion": "omniload.source.notion.api:NotionSource",
        "personio": "omniload.source.personio.api:PersonioSource",
        "phantombuster": "omniload.source.phantombuster.api:PhantombusterSource",
        "pinterest": "omniload.source.pinterest.api:PinterestSource",
        "pipedrive": "omniload.source.pipedrive.api:PipedriveSource",
        "plusvibeai": "omniload.source.plusvibeai.api:PlusVibeAISource",
        "primer": "omniload.source.primer.api:PrimerSource",
        "quickbooks": "omniload.source.quickbooks.api:QuickBooksSource",
        "redditads": "omniload.source.reddit_ads.api:RedditAdsSource",
        "revenuecat": "omniload.source.revenuecat.api:RevenueCatSource",
        "s3": "omniload.source.blobstorage.api:S3Source",
        "salesforce": "omniload.source.salesforce.api:SalesforceSource",
        "sftp": "omniload.source.sftp.api:SFTPSource",
        "shopify": "omniload.source.shopify.api:ShopifySource",
        "slack": "omniload.source.slack.api:SlackSource",
        "smartsheet": "omniload.source.smartsheets.api:SmartsheetSource",
        "snapchatads": "omniload.source.snapchat_ads.api:SnapchatAdsSource",
        "socrata": "omniload.source.socrata.api:SocrataSource",
        "solidgate": "omniload.source.solidgate.api:SolidgateSource",
        "stripe": "omniload.source.stripe.api:StripeAnalyticsSource",
        "tiktok": "omniload.source.tiktok_ads.api:TikTokSource",
        "trustpilot": "omniload.source.trustpilot.api:TrustpilotSource",
        "wise": "omniload.source.wise.api:WiseSource",
        "zendesk": "omniload.source.zendesk.api:ZendeskSource",
        "zeromq+mqb": "omniload.source.mqbridge.api:MqBridgeSource",
        "zoom": "omniload.source.zoom.api:ZoomSource",
    }
)

destinations: LazyRegistry = LazyRegistry(
    {
        "athena": "omniload.target.athena:AthenaDestination",
        "bigquery": "omniload.target.bigquery:BigQueryDestination",
        "clickhouse": "omniload.target.clickhouse:ClickhouseDestination",
        "clickhouse+native": "omniload.target.clickhouse:ClickhouseDestination",
        "cratedb": "omniload.target.cratedb:CrateDBDestination",
        "csv": "omniload.target.csv:CsvDestination",
        "databricks": "omniload.target.databricks:DatabricksDestination",
        "duckdb": "omniload.target.duckdb:DuckDBDestination",
        "elasticsearch": "omniload.target.elasticsearch.api:ElasticsearchDestination",
        "gs": "omniload.target.blobstorage:GCSDestination",
        "md": "omniload.target.motherduck:MotherduckDestination",
        "mongodb": "omniload.target.mongodb:MongoDBDestination",
        "mongodb+srv": "omniload.target.mongodb:MongoDBDestination",
        "motherduck": "omniload.target.motherduck:MotherduckDestination",
        "mssql": "omniload.target.mssql:MsSQLDestination",
        "mysql": "omniload.target.mysql:MySqlDestination",
        "mysql+pymysql": "omniload.target.mysql:MySqlDestination",
        "postgres": "omniload.target.postgresql:PostgresDestination",
        "postgresql": "omniload.target.postgresql:PostgresDestination",
        "postgresql+psycopg2": "omniload.target.postgresql:PostgresDestination",
        "redshift": "omniload.target.redshift:RedshiftDestination",
        "redshift+psycopg2": "omniload.target.redshift:RedshiftDestination",
        "redshift+redshift_connector": "omniload.target.redshift:RedshiftDestination",
        "s3": "omniload.target.blobstorage:S3Destination",
        "snowflake": "omniload.target.snowflake:SnowflakeDestination",
        "sqlite": "omniload.target.sqlite:SqliteDestination",
        "synapse": "omniload.target.synapse:SynapseDestination",
        "trino": "omniload.target.trino:TrinoDestination",
    }
)
