from typing import Dict, Type

from omniload.core.model import DestinationProtocol, SourceProtocol
from omniload.src.sources import (
    AdjustSource,
    AirtableSource,
    AlliumSource,
    AnthropicSource,
    AppleAppStoreSource,
    ApplovinMaxSource,
    AppLovinSource,
    AppsflyerSource,
    ArrowMemoryMappedSource,
    AsanaSource,
    AttioSource,
    BruinSource,
    ChessSource,
    ClickupSource,
    CouchbaseSource,
    CursorSource,
    CustomerIoSource,
    DoceboSource,
    DuneSource,
    DynamoDBSource,
    ElasticsearchSource,
    FacebookAdsSource,
    FirefliesSource,
    FluxxSource,
    FrankfurterSource,
    FreshdeskSource,
    FundraiseupSource,
    GCSSource,
    GitHubSource,
    GoogleAdsSource,
    GoogleAnalyticsSource,
    GoogleSheetsSource,
    GorgiasSource,
    HostawaySource,
    HttpSource,
    HubspotSource,
    IndeedSource,
    InfluxDBSource,
    IntercomSource,
    IsocPulseSource,
    JiraSource,
    KafkaSource,
    KinesisSource,
    KlaviyoSource,
    LinearSource,
    LinkedInAdsSource,
    LocalCsvSource,
    MailchimpSource,
    MixpanelSource,
    MondaySource,
    MongoDbSource,
    NotionSource,
    PersonioSource,
    PhantombusterSource,
    PinterestSource,
    PipedriveSource,
    PlusVibeAISource,
    PrimerSource,
    QuickBooksSource,
    RedditAdsSource,
    RevenueCatSource,
    S3Source,
    SalesforceSource,
    SFTPSource,
    ShopifySource,
    SlackSource,
    SmartsheetSource,
    SnapchatAdsSource,
    SocrataSource,
    SolidgateSource,
    StripeAnalyticsSource,
    TikTokSource,
    TrustpilotSource,
    WiseSource,
    ZendeskSource,
    ZoomSource,
)
from omniload.target.athena import AthenaDestination
from omniload.target.bigquery import BigQueryDestination
from omniload.target.blobstorage import GCSDestination, S3Destination
from omniload.target.clickhouse import ClickhouseDestination
from omniload.target.cratedb import CrateDBDestination
from omniload.target.csv import CsvDestination
from omniload.target.databricks import DatabricksDestination
from omniload.target.duckdb import DuckDBDestination
from omniload.target.elasticsearch import ElasticsearchDestination
from omniload.target.mongodb import MongoDBDestination
from omniload.target.motherduck import MotherduckDestination
from omniload.target.mssql import MsSQLDestination
from omniload.target.mysql import MySqlDestination
from omniload.target.postgresql import PostgresDestination
from omniload.target.redshift import RedshiftDestination
from omniload.target.snowflake import SnowflakeDestination
from omniload.target.sqlite import SqliteDestination
from omniload.target.synapse import SynapseDestination
from omniload.target.trino import TrinoDestination

SQL_SOURCE_SCHEMES = [
    "bigquery",
    "crate",
    "cratedb",
    "duckdb",
    "mssql",
    "mssql+pyodbc",
    "mysql",
    "mysql+pymysql",
    "mysql+mysqlconnector",
    "md",
    "motherduck",
    "postgres",
    "postgresql",
    "postgresql+psycopg2",
    "redshift",
    "redshift+psycopg2",
    "snowflake",
    "sqlite",
    "oracle",
    "oracle+cx_oracle",
    "oracle+oracledb",
    "hana",
    "clickhouse",
    "databricks",
    "db2",
    "spanner",
    "trino",
]


sources: Dict[str, Type[SourceProtocol]] = {
    "allium": AlliumSource,
    "anthropic": AnthropicSource,
    "bruin": BruinSource,
    "csv": LocalCsvSource,
    "couchbase": CouchbaseSource,
    "cursor": CursorSource,
    "docebo": DoceboSource,
    "dune": DuneSource,
    "http": HttpSource,
    "https": HttpSource,
    "mongodb": MongoDbSource,
    "mongodb+srv": MongoDbSource,
    "notion": NotionSource,
    "gsheets": GoogleSheetsSource,
    "shopify": ShopifySource,
    "gorgias": GorgiasSource,
    "github": GitHubSource,
    "chess": ChessSource,
    "stripe": StripeAnalyticsSource,
    "facebookads": FacebookAdsSource,
    "fluxx": FluxxSource,
    "slack": SlackSource,
    "hostaway": HostawaySource,
    "hubspot": HubspotSource,
    "indeed": IndeedSource,
    "intercom": IntercomSource,
    "jira": JiraSource,
    "airtable": AirtableSource,
    "klaviyo": KlaviyoSource,
    "mixpanel": MixpanelSource,
    "appsflyer": AppsflyerSource,
    "kafka": KafkaSource,
    "adjust": AdjustSource,
    "zendesk": ZendeskSource,
    "mmap": ArrowMemoryMappedSource,
    "s3": S3Source,
    "dynamodb": DynamoDBSource,
    "asana": AsanaSource,
    "tiktok": TikTokSource,
    "googleanalytics": GoogleAnalyticsSource,
    "googleads": GoogleAdsSource,
    "appstore": AppleAppStoreSource,
    "gs": GCSSource,
    "linkedinads": LinkedInAdsSource,
    "linear": LinearSource,
    "applovin": AppLovinSource,
    "applovinmax": ApplovinMaxSource,
    "salesforce": SalesforceSource,
    "personio": PersonioSource,
    "kinesis": KinesisSource,
    "pipedrive": PipedriveSource,
    "frankfurter": FrankfurterSource,
    "freshdesk": FreshdeskSource,
    "fundraiseup": FundraiseupSource,
    "trustpilot": TrustpilotSource,
    "phantombuster": PhantombusterSource,
    "elasticsearch": ElasticsearchSource,
    "attio": AttioSource,
    "solidgate": SolidgateSource,
    "quickbooks": QuickBooksSource,
    "isoc-pulse": IsocPulseSource,
    "smartsheet": SmartsheetSource,
    "sftp": SFTPSource,
    "pinterest": PinterestSource,
    "redditads": RedditAdsSource,
    "revenuecat": RevenueCatSource,
    "socrata": SocrataSource,
    "snapchatads": SnapchatAdsSource,
    "zoom": ZoomSource,
    "clickup": ClickupSource,
    "influxdb": InfluxDBSource,
    "wise": WiseSource,
    "plusvibeai": PlusVibeAISource,
    "monday": MondaySource,
    "mailchimp": MailchimpSource,
    "primer": PrimerSource,
    "fireflies": FirefliesSource,
    "customerio": CustomerIoSource,
}
destinations: Dict[str, Type[DestinationProtocol]] = {
    "bigquery": BigQueryDestination,
    "cratedb": CrateDBDestination,
    "databricks": DatabricksDestination,
    "duckdb": DuckDBDestination,
    "motherduck": MotherduckDestination,
    "md": MotherduckDestination,
    "mssql": MsSQLDestination,
    "postgres": PostgresDestination,
    "postgresql": PostgresDestination,
    "postgresql+psycopg2": PostgresDestination,
    "redshift": RedshiftDestination,
    "redshift+psycopg2": RedshiftDestination,
    "redshift+redshift_connector": RedshiftDestination,
    "snowflake": SnowflakeDestination,
    "synapse": SynapseDestination,
    "csv": CsvDestination,
    "athena": AthenaDestination,
    "clickhouse+native": ClickhouseDestination,
    "clickhouse": ClickhouseDestination,
    "elasticsearch": ElasticsearchDestination,
    "mongodb": MongoDBDestination,
    "mongodb+srv": MongoDBDestination,
    "s3": S3Destination,
    "gs": GCSDestination,
    "sqlite": SqliteDestination,
    "mysql": MySqlDestination,
    "mysql+pymysql": MySqlDestination,
    "trino": TrinoDestination,
}
